data:
  num_classes: 2
  root_dirs:
    - "E:\\data3d\\nodule_patches96_1"
    - "E:\\data3d\\nodule_patches96_2"
    - "E:\\data3d\\nodule_patches96_3"
    - "E:\\data3d\\nodule_patches96_4"
  output_dir: Relapse_train_output
  class_names:
    - Invasive
    - Non-invasive
model:
  params:
    image_size: 96
    patch_size: 6
    dim: 384
    depth: 6
    heads: 6
    mlp_dim: 256
    mlp_num: 2
    pool: max
    cpt_num: 100

training:
  device: cuda
  random_seed: 42
  batch_size: 64
  num_epochs: 30
  num_workers: 4
  use_amp: false
  cache_dataset: true
  warmup_epochs: 3
  warmup_type: linear
  max_grad_norm: 1.0
  crop_size: 48
  augment: true
  pretrained_path: "E:\\workplace\\3D\\src\\train_output\\train_20250327_094426\\best_f1_model.pth"
  frozen: True
losses:
  CrossEntropyLoss:
    enabled: false
    weight: 1.0
    params:
  FocalLoss:
    enabled: true
    weight: 1.0
    params:
      gamma: 2.0
      alpha: 0.25
  BoundaryFlowLoss:
    enabled: false
    weight: 1.0
    params:
      weight: 0.5
      margin: 0.3
  SimilarityLoss:
    enabled: false
    params:
      low: 0.3
      high: 0.7
cross_validation:
  n_splits: 10
  shuffle: true
optimizer:
  name: AdamW
  params:
    lr: 0.00002
    weight_decay: 0.002
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 30
    eta_min: 5e-7
