# 多模态复发预测与分类多任务模型配置
data:
  num_classes: 2  # 复发预测类别数
  num_classes_subtype: 3  # 肿瘤亚型分类类别数
  root_dirs:
    - 'E:\data3D\nodule_patches96_1'
    - 'E:\data3D\nodule_patches96_2'
    - 'E:\data3D\nodule_patches96_3'
    - 'E:\data3D\nodule_patches96_4'
  output_dir: 'mul_train_output'
  class_names: ['Invasive', 'Non-invasive']
  subtype_class_names: ['低分化', '中分化', '高分化', '原位癌', '微浸润']
  csv_path: 'E:\workplace\3D\datasets\structured_results_deepseek_补全CT报告.csv'
  max_text_length: 512

model:
  params:
    image_size: [96, 96, 96] # 96 * 96 * 96
    patch_size: 8
    dim: 768
    depth: 12
    heads: 12
    mlp_dim: 128
    mlp_num: 2
    pool: 'max' # mean max all
    cpt_num: 20
  bert_model_name: 'E:\workplace\3D\pred_model\bert_chinese'
  tokenizer_path: 'E:\workplace\3D\pred_model\bert_chinese'
  text_feature_dim: 768
  fusion_dim: 768
  dropout: 0.5
  prompt_num: 0  # 提示向量数量
  fusion_method: "attention"  # attention, concat, sum

training:
  device: "cuda"
  random_seed: 42
  batch_size: 32  # 降低批次大小以适应多模态
  num_epochs: 20
  num_workers: 2
  use_amp: true
  cache_dataset: True
  warmup_epochs: 5
  warmup_type: "linear"
  max_grad_norm: 1.0
  crop_size: [64, 64, 32]
  augment: true
  pretrained_path: 'E:\workplace\3D\src\train_output\train_20250617_210403\best_auc_model_1.pth'
  bert_pretrained_path: 'E:\workplace\3D\pred_model\bert_chinese' # 如果有预训练的BERT模型，可以在这里指定
  frozen1: true # 冻结图像编码器
  frozen2: true # 冻结文本编码器
  frozen_prompt: false  # 不冻结提示向量

losses:
  CrossEntropyLoss:
    enabled: true
    weight: 1.0
    params: {0.3, 0.7}
  FocalLoss:
    enabled: false
    weight: 1.0
    params:
      gamma: 2.0
      alpha: 0.25
  BoundaryFlowLoss:
    enabled: true
    weight: 1.0
    params:
      weight: 0.5
      margin: 0.3
  SimilarityLoss:
    enabled: false
    params:
      low: 0.3
      high: 0.7
  MultitaskLoss:
    enabled: true
    recurrence_weight: 1.0  # 复发预测任务权重
    subtype_weight: 0.5   # 亚型分类任务权重


cross_validation:
  n_splits: 10
  shuffle: true
  negative_ratio: 8
  pos_ratio: 0.2
  minority_multiplier: 6
  use_clustering: false  # 设置为true启用聚类交叉验证
  clustering_method: "kmeans"  # 聚类方法
  feature_extraction_batch_size: 32  # 特征提取时的批次大小

optimizer:
  name: "AdamW"
  params:
    lr: 0.00001
    weight_decay: 0.0001

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 20
    eta_min: 5e-6