# 多模态复发预测与分类多任务模型配置
data:
  num_classes: 2  # 复发预测类别数
  num_classes_subtype: 3  # 肿瘤亚型分类类别数
  root_dirs:
    - 'E:\data3D\nodule_patches96_1'
    - 'E:\data3D\nodule_patches96_2'
    - 'E:\data3D\nodule_patches96_3'
    - 'E:\data3D\nodule_patches96_4'
  output_dir: 'mul_train_output'
  class_names: ['Invasive', 'Non-invasive']
  subtype_class_names: ['低分化', '中分化', '高分化', '原位癌', '微浸润']
  csv_path: '../datasets/CTreport/协和预后随访复发与否.csv'
  max_text_length: 512

model:
  params:
    image_size: 96 # 96 * 96 * 96
    patch_size: 6
    dim: 384
    depth: 6
    heads: 6
    mlp_dim: 256
    mlp_num: 1
    pool: 'max' # mean max all
    cpt_num: 50
  bert_model_name: 'E:\workplace\3D\pred_model\bert_chinese'
  text_feature_dim: 384
  fusion_dim: 384
  dropout: 0.5
  prompt_num: 5  # 提示向量数量
  fusion_method: "concat"  # attention, concat, sum

training:
  device: "cuda"
  random_seed: 42
  batch_size: 16  # 降低批次大小以适应多模态
  num_epochs: 20
  num_workers: 4
  use_amp: false
  cache_dataset: True
  warmup_epochs: 3
  warmup_type: "linear"
  max_grad_norm: 1.0
  crop_size: 42
  augment: True
  pretrained_path: 'E:\workplace\3D\src\train_output\best\train_20250416_110325\best_f1_model_1.pth'
  bert_pretrained_path: 'E:\workplace\3D\pred_model\bert' # 如果有预训练的BERT模型，可以在这里指定
  frozen: false  # 冻结图像和文本编码器主干
  frozen_prompt: false  # 不冻结提示向量

losses:
  CrossEntropyLoss:
    enabled: false
    weight: 1.0
    params: {0.3, 0.7}
  FocalLoss:
    enabled: True
    weight: 1.0
    params:
      gamma: 2.0
      alpha: 0.25
  BoundaryFlowLoss:
    enabled: false
    weight: 1.0
    params:
      weight: 0.5
      margin: 0.3
  SimilarityLoss:
    enabled: false
    params:
      low: 0.3
      high: 0.7
  MultitaskLoss:
    enabled: true
    recurrence_weight: 1.0  # 复发预测任务权重
    subtype_weight: 1.0     # 亚型分类任务权重

cross_validation:
  n_splits: 5
  shuffle: true

optimizer:
  name: "AdamW"
  params:
    lr: 0.00002
    weight_decay: 0.05

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 20
    eta_min: 5e-6