data:
  num_classes: 2
  root_dirs:
    - 'G:\datasets3D\nodule_patches96_1'
  output_dir: 'test_result'
#  class_names: ['低分化', '中分化', '高分化', '微浸润', '原位癌']
  class_names: ['Invasive', 'Non-invasive']


model:
  params:
    image_size: 96 # 96 * 96 * 96
    patch_size: 6
    dim: 384
    depth: 6
    heads: 12
    mlp_dim: 256
    pool: 'max' # mean max all

training:
  device: "cuda"
  random_seed: 42
  batch_size: 64
  num_epochs: 30
  num_workers: 2
  use_amp: False   # 当输出值特别大或者特别小时，  会影响softmax结果，导致概率之和不为1。
  cache_dataset: True
  warmup_epochs: 3
  warmup_type: "linear"
  max_grad_norm: 1.0
  crop_size: 36
  augment: False
  pretrained_path: 'E:\workplace\3D\src\train_output\train_20\best_auc_model_fold_4.pth'
  loss:
    smoothing: 0.1
    class_weights: "auto"

cross_validation:
  n_splits: 5
  shuffle: true

optimizer:
  name: "AdamW"
  params:
    lr: 0.00005
    weight_decay: 0.05

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 30
    eta_min: 5e-7