data:
  num_classes: 2
  root_dirs:
    - "E:\\data3D\\nodule_patches96_1"
    - "E:\\data3D\\nodule_patches96_2"
    - "E:\\data3D\\nodule_patches96_3"
    - "E:\\data3D\\nodule_patches96_4"
    - "E:\\data3D\\nodule_patches96_5"
  output_dir: train_output
  class_names:
    - Invasive
    - Non-invasive
model:
  params:
    image_size: [96, 96, 96]
    patch_size: 8
    dim: 768   # 384 768
    depth: 12   # 6 8 12
    heads: 12  # 6 8 12
    mlp_dim: 128
    mlp_num: 2  #  1 2 3
    pool: max
    cpt_num: 2  # 2 5 10 50 100

training:
  device: cuda
  random_seed: 42
  batch_size: 64
  num_epochs: 10
  num_workers: 4
  use_amp: true
  cache_dataset: true
  warmup_epochs: 3
  warmup_type: linear
  max_grad_norm: 1.0
  crop_size: [64, 64, 32]    # [H, W, D]
  augment: true
  pretrained_path: "../pred_model/rad_dino"
  frozen: false
  frozen1: false
  frozen2: false

losses:
  CrossEntropyLoss:
    enabled: True
    weight: 1.0
    params:
  FocalLoss:
    enabled: false
    weight: 1.0
    params:
      gamma: 2.0
      alpha: 0.25
  BoundaryFlowLoss:
    enabled: false
    weight: 0.3
    params:
      weight: 0.7
      margin: 0.3
  SimilarityLoss:
    enabled: true
    params:
      low: 0.3
      high: 0.7

cross_validation:
  n_splits: 5
  shuffle: true
optimizer:
  name: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.0001
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 20
    eta_min: 5e-6
