data:
  root_dirs:
    - 'G:\datasets3D\nodule_patches96_1'
    - 'G:\datasets3D\nodule_patches96_2'
    - 'G:\datasets3D\nodule_patches96_3'

model:
  params:
    image_size: [96, 96, 96]
    patch_size: 16
    dim: 768
    depth: 12
    heads: 12
    mlp_dim: 3072

training:
  device: "cuda"
  random_seed: 42
  batch_size: 16
  num_epochs: 50
  num_workers: 4
  use_amp: True
  cache_dataset: True
  warmup_epochs: 3
  warmup_type: "linear"
  max_grad_norm: 1.0
  center_crop: "64x64x64"
  augment: True
  loss:
    smoothing: 0.1
    class_weights: "auto"

cross_validation:
  n_splits: 5
  shuffle: true

optimizer:
  name: "AdamW"
  params:
    lr: 3e-4
    weight_decay: 0.01

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 50
    eta_min: 1e-6